### ISSUE TITLE
How to use it with pub returning one object

### ISSUE THREAD

**Issue by jalalat** [Urigo/meteor-rxjs#18]
How to use this package when Pub is returning only one object (one row/record) and I try to get it using say Posts.findOne(postId);

**Comment by dotansimha** [comment]
Hi @jalalat ,
You can either use `collection.findOne(...)` and get the actual value directly, but it's not recommended because you won't be able to know when the collection actually change, only the specific item, and I will recommend you to use it only after the Meteor subscription is ready, example:
```js
MeteorObservable.subscribe("data").subscribe(() => {
     // Subscription is ready
     let myItem = MyCollection.findOne(...);
});
```

You can also use regular `collection.find(...)` and then the subscription of the data will return an Array with a single item, for example:
MeteorObservable.subscribe("data").subscribe(() => {
     let myItem;
     // Subscription is ready
     MyCollection.find().subscribe((data) => { 
           myItem = data[0];
     });
});

Please re-open the issue if you have another questions.
