### ISSUE TITLE
Are there any plans to add Observable complete functionality?

### ISSUE THREAD

**Issue by cesargalindo** [Urigo/meteor-rxjs#25]
Are there any plans to add Observable complete functionality?

Angular HTTP returns completed observables when returned from the server.   Observables returned from meteor-rxjs are returned as not complete.    Consequently, many features of rxjs are not usable such as concat, take, etc..   It would be ideal to provide a flag "option" to return completed observables..

this.http.get('/orders')
   .subscribe(
         data => this.orders = data,
         error => console.log(error),
         () => { alert('finished!'); } // <- this called with Angular http
   );

**Comment by dotansimha** [comment]
@cesargalindo 
What does the difference between `next` callback and `complete` callback in Angular 2 http module?
Because the `next` does not called on progress, but for data, and complete called right after, so it's basically the same callback (see https://github.com/angular/angular/blob/2b5c983c13c892d59f8e1bf223c291cbc3a40d8a/modules/%40angular/http/src/backends/xhr_backend.ts#L84-L86).

In this package's implementation, we does the same - then `Meteor.call` returns we call both (https://github.com/Urigo/meteor-rxjs/blob/master/src/MeteorObservable.ts#L61-L62).
In `Meteor.subscribe`, we don't want to call `complete` callback because it will unsubscribe from the Meteor subscription.

So which API does not complete?

**Comment by cesargalindo** [comment]
@dotansimha 

thanks for the reply.  So it appears I have to use Meteor.call to leverage the complete callback?

It appears both `next` and `complete` are called in the Angular2 http module.
-------------xhr_backend.js-------
```
                if (response.ok) {
                    responseObserver.next(response);
                    // TODO(gdi2290): defer complete if array buffer until done
                    responseObserver.complete();
                    return;
                }
                responseObserver.error(response);
```

....................jsonp_backen.js-------
```
              responseObserver.next(new Response(responseOptions));
              responseObserver.complete();
```

Would be nice if there was an option to request some sort of complete on a Meteor.subscription each time the this.data.subscribe(...)  is manually called?  It would psuedo-complete on the first response from the server.   

```
this.data.subscribe(
     data => this.orders = data,
     error => console.log(error),
     () => {  console.log('complete');  } 
);
```

**Comment by cesargalindo** [comment]
@dotansimha
The key difference I see from Meteor.subscribe and Angular HTTP subscribe is
Angular HTTP subscribe returns the response as one object "large array"  in  .subscribe()  whereas Meteor.subscribe is breaks the response into individual elements of the parent array.

It would be beneficial "at least to me?"  to return the response from the server as one object/array.  This way I can better leverage it with promises, async/await, futures/fibers, etc..

In essence I would treat the observable as ready to act on data when a response is received.


```
this.data.subscribe(
     data => this.orders = data,
     error => console.log(error),
     () => {  console.log('complete');  } 
);
```

**Comment by dotansimha** [comment]
@cesargalindo, the is a difference between Meteor's subscriptions and Angular 2 Http service:
- Angular 2 http executed and returns `Observable` which resolves into the data returned from the http request (calls both - next and complete callbacks). Also, this data is not reactive and does not behave as stream - once the http request is returned - the stream comes to an end - so the `complete` callback called.
This behavior is similar to `MeteorObservable.call`, you call a method and get a response, without any reactive or stream (that's why we call `complete` after `next`).

- Meteor subscriptions doesn't have anything to do with the data - `Meteor.subscribe` callbacks are only for `onReady` (which is the `next` and `complete`) or `onError` and the effect of the subscription is only in the `Mongo.Collection` - there is where the data is stored - and because this collection is reactive, we treat this type of Collection as stream of data and there is no reason to call `complete` on the Collection data changes. 

```
MeteorObservable.subscribe("myData").subscribe(() => {
    // Subscription is ready and the all the subscription data is available on the client
    // Same as onReady callback using regular Meteor
}, (err) => {
    // In case of an error creating the Meteor subscription - same as onError callback
}, () => {
    // Called right after next callback - the subscription is complete are ready to use.
});

let myData = MyCollection.find({});
myData.subscribe((data) => {
    // Reactive callback - called for each change in the data of the collection
}, (err) => {
   // In case of error with the collection or the cursor
}, () => {
   // Called when you dispose the subscription for the data 
})
```

**Comment by cesargalindo** [comment]
Thanks @dotansimha ,  it all much clearer now and I was able to get around my issue dealing with observables, cursors, reactivity, onReady/complete, etc..

**Comment by dotansimha** [comment]
You are welcome!

**Comment by clitetailor** [comment]
First, i think this is ok but then i think this API is stupid (sorry for saying this). For example:

```javascript

**Comment by clitetailor** [comment]
First, I think this ok but now i think the API is quite stupid (sorry for this). For example:

```javascript
// server
Meteor.publish('topics', function () {
	return Topics.find({});
})
```

```javascript
// client
Topics.find({}).subscribe(topics => this.topics = topics);

this.topicSubscription = MeteorObservable.subscribe('topics').subscribe();
```

Why i have to subscribe and unsubscribe twice to get the data or in better example:

```javascript
\\ client
MeteorObservable.subscribe('topics').subscribe(() => {
	this.topics = Topics.find({}).fetch();
});
```

Why we have to query data twice, what is the meaning of publishing here?. We have already subscribe a listener, why can't we just get data directly from the cursor or from the listener instead of `find` and `fetch`?

I propose a better API here:

```javascript
MeteorObservable.subscribe('topics').toPromise().then(topics => this.topics = topics);
```

Or

```javascript
MeteorObservable.subscribe('topics').subscribe(() => {
    this.topics = Topics.currentValue()
})
```
