### ISSUE TITLE
Collection.find doesn't call map when result is empty

### ISSUE THREAD

**Issue by ppoliani** [Urigo/meteor-rxjs#31]
I'm experiencing currently an issue when trying to map over an empty result set.

For example, when I try to do:

    Collection.find(condition).map(x => ....)

the map callback will not be called if the result of find is empty.

Is that behaviour according to the design?

**Comment by dotansimha** [comment]
If there is no data in the Mongo.Collection, then the changes events won't fire, and the `next` callback of the Observable won't fire. 
You can use RxJS [startWith](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/startwith.md) operator in order to solve it:
```
Collection.find(condition).startWith([]).map(x => ....)
```

**Comment by jerradpatch** [comment]
I personally expected it to return an empty array when nothing was in the collection or at least a null. Is there a reason why it doesn't do this by default?

**Comment by atd** [comment]
I agree with @jerradpatch Otherwise, there is no way to distinguish between the two cases (data isn't loaded yet vs data is loaded but empty)

It is needed to avoid showing users the empty placeholders in lists, which is confusing (user sees a notice saying that her list is empty, and then the list populates with data)

There is a pull request fixing it https://github.com/Urigo/meteor-rxjs/pull/103
